export const BASE_URL = (process.env.REACT_APP_API_URL !== undefined) ? process.env.REACT_APP_API_URL :  "http://localhost:3000"
export const V1_PREFIX = '/api/v1'
export const LOGIN_URL = '/oauth/token'
export const VISIBLE_WIDGETS_URL = '/widgets/visible'
export const REVOKE_TOKEN_URL = '/oauth/revoke'
export const USERS_URL = '/users'
export const RESET_PASSWORD_URL = '/users/reset_password'
export const USERS_ME_URL = '/users/me'
export const USERS_CHANGE_PASSWORD_URL= '/users/me/password'
export const WIDGETS_URL = '/widgets'
export const USERS_WIDGETS_URL = '/users/me/widgets'