export const SET_VISIBLE_WIDGETS = "WIDGETS_SET_VISIBLE_WIDGETS";
export const RESET_VISIBLE_WIDGETS = "WIDGETS_RESET_VISIBLE_WIDGETS";
export const SET_WIDGETS = "WIDGETS_SET_WIDGETS";
export const REMOVE_VISIBLE_WIDGET = "WIDGETS_REMOVE_VISIBLE_WIDGET";